project_id = "tnjqqaasmrkiaxnmkpcn"

[functions.process-technical-document]
verify_jwt = false

[functions.technical-assistant-chat]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.analyze-cable-image]
verify_jwt = false

[functions.analyze-report]
verify_jwt = false