/// <reference lib="webworker" />

import { clientsClaim } from "workbox-core";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { ExpirationPlugin } from "workbox-expiration";
import { registerRoute } from "workbox-routing";
import { CacheFirst, NetworkFirst, NetworkOnly, StaleWhileRevalidate } from "workbox-strategies";

declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision?: string }>;
};

// FORCE NEW VERSION - Change this value to invalidate old SW
const SW_VERSION = "v2024-12-18-001";
console.log(`[SW] Activating Service Worker ${SW_VERSION}`);

self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// App Shell (SPA) navigation: prefer network to avoid stale versions; fall back to cache when offline.
registerRoute(
  ({ request }) => request.mode === "navigate",
  new NetworkFirst({
    cacheName: "html-cache",
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 }),
    ],
  })
);

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Fonts caching
registerRoute(
  ({ url }) => url.origin === "https://fonts.googleapis.com",
  new StaleWhileRevalidate({
    cacheName: "google-fonts-cache",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  })
);

registerRoute(
  ({ url }) => url.origin === "https://fonts.gstatic.com",
  new CacheFirst({
    cacheName: "gstatic-fonts-cache",
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Always fetch backend API fresh (no SW caching)
registerRoute(
  ({ url }) => url.hostname.endsWith(".supabase.co"),
  new NetworkOnly()
);

// Push notifications
self.addEventListener("push", (event) => {
  let data: {
    title?: string;
    body?: string;
    icon?: string;
    badge?: string;
    data?: any;
  } = {
    title: "Ropes 360",
    body: "Nova notificação",
    icon: "/pwa-192x192.png",
    badge: "/pwa-192x192.png",
  };

  if (event.data) {
    try {
      data = event.data.json();
    } catch {
      // ignore parse errors and fall back to defaults
    }
  }

  const options: NotificationOptions & { vibrate?: number[] } = {
    body: data.body,
    icon: data.icon || "/pwa-192x192.png",
    badge: data.badge || "/pwa-192x192.png",
    data: data.data,
    vibrate: [200, 100, 200],
    tag: data.data?.notification_id || "notification",
    requireInteraction: true,
  };

  event.waitUntil(self.registration.showNotification(data.title || "Ropes 360", options));
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const relativePath = event.notification.data?.related_module
    ? `/${event.notification.data.related_module}`
    : "/";

  const urlToOpen = new URL(relativePath, self.location.origin).href;

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url === urlToOpen && "focus" in client) {
            return client.focus();
          }
        }
        if (self.clients.openWindow) return self.clients.openWindow(urlToOpen);
      })
  );
});

export {};