// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_my_services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_services_default = defineTool({
  name: "list_my_services",
  title: "List my services",
  description: "List service (JBR) records the signed-in user can access, ordered by most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max rows to return."),
    search: z.string().trim().optional().describe("Optional case-insensitive substring to match against JBR code or client name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("services").select("id, codigo_jbr, cliente, equipamentos, aplicacao, local, data_inicio, data_termino, created_at").order("created_at", { ascending: false }).limit(limit);
    if (search) query = query.or(`codigo_jbr.ilike.%${search}%,cliente.ilike.%${search}%`);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_my_notifications.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.74.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool2({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's notifications, most recent first.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20),
    unread_only: z2.boolean().default(false)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser2(ctx).from("notifications").select("id, title, message, type, is_read, related_module, related_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_my_certifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.74.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_certifications_default = defineTool3({
  name: "list_my_certifications",
  title: "List my certifications",
  description: "List the signed-in user's certifications with their expiry dates. Useful to check what is expiring.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("certifications").select("id, certification_name, expiry_date, file_name, created_at").eq("user_id", ctx.getUserId()).order("expiry_date", { ascending: true }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { certifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_my_reports.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.74.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_reports_default = defineTool4({
  name: "list_my_inspection_reports",
  title: "List my inspection reports",
  description: "List inspection reports the signed-in user can access, most recent first. Excludes the large report_data payload.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).default(20),
    status: z4.string().trim().optional().describe("Optional exact status filter (e.g. draft, completed).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser4(ctx).from("inspection_reports").select("id, report_number, title, status, created_at, updated_at, completed_at").order("updated_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tnjqqaasmrkiaxnmkpcn";
var mcp_default = defineMcp({
  name: "ropes360-mcp",
  title: "Ropes 360 \u2014 Hub de Inspetores",
  version: "0.1.0",
  instructions: "Tools for Ropes 360 (Bridon-Bekaert Hub de Inspetores). All tools run as the signed-in user and respect row-level security. Use them to look up the user's services (JBR), inspection reports, certifications, and notifications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_services_default, list_my_reports_default, list_my_certifications_default, list_my_notifications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
